# Kali-Docker Configuration
# Current setup configuration

# Docker Host
DOCKER_HOST_IP=172.20.0.1
DOCKER_NETWORK=172.20.0.0/16
SECURE_NET=internal
ISOLATED_NET=internal

# Services
KALI_DNS_PORT=53
KALI_WEB_PORT=80
HAPROXY_HTTP=80
HAPROXY_HTTPS=443
WIREGUARD_PORT=51820
WIREGUARD_SUBNET=10.0.0.0/24
WIREGUARD_PEERS=1

# TLS/SSL
DOCKER_TLS_CERTDIR=/etc/docker/certs
DOH_CERT=/etc/ssl/certs/haproxy.pem

# Profiles
SERVICES_PROFILE=dns,doh,ingress,vpn

# Environment
TZ=Etc/UTC
PUID=1000
PGID=1000

# Monitoring
FLUENT_BIT_PORT=24224
PROMETHEUS_PORT=9090
GRAFANA_PORT=3000